import mysql from "mysql2/promise";

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// Bio data for all 36 governor races
// Sources: Ballotpedia, Wikipedia, Cook Political Report, Inside Elections (Apr 2026)
const bioupdates = [
  // ── TOSS-UP RACES ──────────────────────────────────────────────────────────
  {
    stateCode: "AZ",
    demCandidate: "Katie Hobbs",
    repCandidate: "Andy Biggs",
    demPreviousOffice: "Governor of Arizona (2023–present); former AZ Secretary of State (2019–2023)",
    repPreviousOffice: "U.S. Representative, AZ-5 (2017–2025); former AZ State Senate President",
    demBio: "Katie Hobbs (D) was elected Arizona's 24th governor in 2022, defeating Kari Lake by just 17,117 votes — the narrowest statewide margin in Arizona history. A social worker by training, she previously served as Arizona Secretary of State and as a state legislator. She has focused her term on water conservation, reproductive rights, and economic development. Hobbs is seeking a second term in a state that has trended competitive in recent cycles.",
    repBio: "Andy Biggs (R) is a former U.S. Representative from Arizona's 5th congressional district and a founding member of the House Freedom Caucus. A staunch Trump ally, he served as Arizona State Senate President before going to Congress. He is running on a platform of border security, tax cuts, and rolling back state regulations. Biggs is considered the frontrunner in the Republican primary.",
    notes: "Cook: Toss-up; IE: Toss-up; Sabato: Lean D (Mar 2026). Hobbs won 2022 by 0.6%. Trump carried AZ by 5.5pts in 2024, making this a true battleground.",
  },
  {
    stateCode: "MI",
    demCandidate: "Jocelyn Benson",
    repCandidate: "John James",
    demPreviousOffice: "Michigan Secretary of State (2019–present); former Dean, Wayne State Law School",
    repPreviousOffice: "U.S. Representative, MI-10 (2023–2025); Army veteran; CEO, James Group International",
    demBio: "Jocelyn Benson (D) has served as Michigan's Secretary of State since 2019, earning national recognition for her administration of the 2020 and 2022 elections. A voting rights advocate and former law school dean, she is running to succeed term-limited Gov. Gretchen Whitmer. She has centered her campaign on protecting abortion rights, expanding education funding, and continuing Whitmer's economic agenda.",
    repBio: "John James (R) is a West Point graduate, Army Black Hawk helicopter pilot, and Iraq War veteran who ran unsuccessfully for U.S. Senate in 2018 and 2020 before winning a House seat in 2022. He is the CEO of his family's automotive supply company. James ran a competitive 2024 House race and is considered the frontrunner in the Republican primary for governor.",
    notes: "Cook: Toss-up; IE: Toss-up; Sabato: Toss-up. Open seat — Whitmer is term-limited. Trump won MI by 1.4pts in 2024. One of the most competitive governor races in the country.",
  },
  {
    stateCode: "WI",
    demCandidate: "Mandela Barnes",
    repCandidate: "Eric Hovde",
    demPreviousOffice: "Former Lieutenant Governor of Wisconsin (2019–2023); former WI State Assembly member",
    repPreviousOffice: "Businessman; CEO, Sunstone Hotel Investors; 2022 Republican Senate nominee (lost to Baldwin by 1pt)",
    demBio: "Mandela Barnes (D) served as Wisconsin's Lieutenant Governor under Tony Evers from 2019 to 2023. He ran for U.S. Senate in 2022, losing to Sen. Tammy Baldwin by just 1 point in a cycle that favored Republicans. A Milwaukee native, Barnes has focused his campaign on economic opportunity, healthcare access, and criminal justice reform. He is considered the frontrunner in the Democratic primary.",
    repBio: "Eric Hovde (R) is a Wisconsin-born businessman and bank executive who came within 1 point of defeating Sen. Tammy Baldwin in 2022. He is the CEO of Sunstone Hotel Investors and a major Republican donor. Hovde is running on a platform of fiscal conservatism, border security, and opposition to what he calls 'Madison liberal policies.' He is the frontrunner in the Republican primary.",
    notes: "Cook: Toss-up; IE: Toss-up; Sabato: Toss-up. Open seat — Evers chose not to seek re-election. Trump won WI by 0.9pts in 2024. Potentially the most competitive governor race of 2026.",
  },
  {
    stateCode: "KS",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Kansas Democrats are fielding candidates to replace term-limited Gov. Laura Kelly, who won two terms as a Democrat in a heavily Republican state. The Democratic primary field is still forming. Kelly's wins demonstrated that a moderate Democrat can win statewide in Kansas, but the state has trended more Republican at the federal level.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Laura Kelly. Kansas has a Republican-dominated legislature and has voted for Republican presidential candidates by large margins, making the GOP nominee the heavy favorite in November. The primary is scheduled for August 4, 2026.",
    notes: "Cook: Likely R; IE: Likely R; Sabato: Likely R. Open seat — Kelly is term-limited. Kansas has a history of electing moderate Democrats governor even as it votes Republican federally, but this race leans Republican.",
  },
  // ── LEAN D RACES ──────────────────────────────────────────────────────────
  {
    stateCode: "GA",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Georgia Democrats are competing in a crowded primary to succeed term-limited Gov. Brian Kemp. Several prominent Democrats have entered the race, energized by the state's competitive presidential and Senate results in recent cycles. The Democratic primary is scheduled for May 19, 2026.",
    repBio: "Multiple Republicans are competing to succeed term-limited Gov. Brian Kemp, who won re-election by 8 points in 2022. Kemp's departure creates an open seat in a state that has become increasingly competitive at the statewide level. The Republican primary is scheduled for May 19, 2026.",
    notes: "Cook: Toss-up; IE: Toss-up; Sabato: Toss-up. Open seat — Kemp is term-limited. Georgia is a true battleground — Biden won it in 2020, Trump won it by 2.2pts in 2024.",
  },
  {
    stateCode: "ME",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Maine Democrats are competing in the primary to succeed term-limited Gov. Janet Mills, who won two terms as a moderate Democrat. Maine has elected Democratic governors in recent cycles and Democrats have an advantage in the state's more populous southern counties. The primary is June 9, 2026.",
    repBio: "Maine Republicans are competing in the primary, hoping to flip the governorship after two terms of Democratic control under Janet Mills. The state has a history of electing independent and moderate candidates, and the Republican nominee will need to appeal to the state's large independent voter bloc.",
    notes: "Cook: Toss-up; IE: Tilt R; Sabato: Toss-up. Open seat — Mills is term-limited. Maine uses ranked-choice voting for governor. Competitive race with no clear frontrunner yet.",
  },
  {
    stateCode: "MN",
    demCandidate: "TBD (DFL Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Minnesota DFL (Democratic-Farmer-Labor) candidates are competing in the primary to succeed Gov. Tim Walz, who chose not to seek re-election after his 2024 vice-presidential run. Minnesota has voted Democratic in every presidential election since 1976, and Democrats hold a structural advantage in the state. The DFL primary is August 11, 2026.",
    repBio: "Minnesota Republicans are competing in the primary, hoping to end the DFL's hold on the governorship. The state has trended slightly more competitive in recent federal elections, and Republicans see an opportunity with an open seat. The Republican primary is August 11, 2026.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Open seat — Walz chose not to seek re-election. Minnesota has not elected a Republican governor since 2002 (Tim Pawlenty). Democrats are favored.",
  },
  {
    stateCode: "NM",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "New Mexico Democrats are competing to succeed term-limited Gov. Michelle Lujan Grisham, who has served two terms. New Mexico has voted Democratic in every presidential election since 2008 and Democrats hold a significant registration advantage. The Democratic primary is June 2, 2026.",
    repBio: "New Mexico Republicans are competing in the primary, hoping to flip the governorship in a state that has trended increasingly Democratic. Republicans have not won the governorship since Susana Martinez in 2010 and 2014. The Republican primary is June 2, 2026.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Open seat — Lujan Grisham is term-limited. New Mexico has a strong Democratic lean at the statewide level.",
  },
  {
    stateCode: "OH",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Vivek Ramaswamy",
    demPreviousOffice: null,
    repPreviousOffice: "2024 Republican presidential candidate; co-founder and CEO, Roivant Sciences; founder, Strive Asset Management",
    demBio: "Ohio Democrats are competing in the primary to challenge the Republican nominee. Ohio has trended Republican in recent cycles — Trump won it by 11 points in 2024 — making this a difficult environment for Democrats. However, Democrats have shown strength in statewide ballot measures on issues like abortion rights.",
    repBio: "Vivek Ramaswamy (R) is a biotech entrepreneur and author who ran for the 2024 Republican presidential nomination, finishing third in the Iowa caucuses before dropping out and endorsing Donald Trump. He co-founded Roivant Sciences and Strive Asset Management. Ramaswamy has launched a $10 million ad campaign and is considered the frontrunner in the Republican primary. He has selected state Sen. Matt Huffman as his running mate.",
    notes: "Cook: Likely R; IE: Likely R; Sabato: Likely R. Open seat — DeWine is term-limited. Trump won OH by 11pts in 2024. Ramaswamy is the frontrunner in the Republican primary.",
  },
  // ── LIKELY D RACES ──────────────────────────────────────────────────────────
  {
    stateCode: "NY",
    demCandidate: "Kathy Hochul",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of New York (2021–present); former Lieutenant Governor; former U.S. Representative, NY-26",
    repPreviousOffice: null,
    demBio: "Kathy Hochul (D) became New York's first female governor in August 2021 when Andrew Cuomo resigned. She won a full term in 2022 by 5.7 points over Rep. Lee Zeldin in a closer-than-expected race. A moderate Democrat from Buffalo, Hochul has focused on housing, public safety, and economic development. She is seeking her second full term.",
    repBio: "The Republican field for New York governor is still forming. New York has not elected a Republican governor since George Pataki in 2002. The Republican nominee will face a significant structural disadvantage in a state where Democrats outnumber Republicans by more than 2 million registered voters.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Hochul won 2022 by 5.7pts. New York has not elected a Republican governor since 2002. Democrats are favored.",
  },
  {
    stateCode: "PA",
    demCandidate: "Josh Shapiro",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Pennsylvania (2023–present); former PA Attorney General (2017–2023); former PA State Representative",
    repPreviousOffice: null,
    demBio: "Josh Shapiro (D) won the Pennsylvania governorship in 2022 by 14.8 points, the largest margin in a competitive Pennsylvania statewide race in decades. A former state legislator and two-term Attorney General, Shapiro has been widely praised for his bipartisan approach and was considered a potential 2024 vice-presidential pick. He is seeking re-election in a state that has been a presidential battleground.",
    repBio: "Pennsylvania Republicans are competing in the primary to challenge Gov. Josh Shapiro. Shapiro's strong approval ratings and large 2022 margin make him a formidable incumbent. Republicans will need to find a candidate who can appeal to both the Trump base and moderate suburban voters.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Shapiro won 2022 by 14.8pts. He is one of the most popular governors in the country and is considered a strong favorite for re-election.",
  },
  {
    stateCode: "OR",
    demCandidate: "Tina Kotek",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Oregon (2023–present); former Oregon House Speaker (2013–2023)",
    repPreviousOffice: null,
    demBio: "Tina Kotek (D) won the Oregon governorship in 2022 with 47% of the vote in a three-way race, defeating Republican Christine Drazan and independent Betsy Johnson. Oregon's first openly lesbian governor, she previously served as Oregon House Speaker for a decade. She has focused on housing affordability, homelessness, and behavioral health.",
    repBio: "Oregon Republicans are competing in the primary to challenge Gov. Tina Kotek. Oregon has voted Democratic in every presidential election since 1984 and has a strong Democratic lean at the statewide level. The Republican nominee will face a structural disadvantage.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Kotek won 2022 with 47% in a three-way race. Oregon has a strong Democratic lean.",
  },
  {
    stateCode: "RI",
    demCandidate: "Dan McKee",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Rhode Island (2021–present); former Lieutenant Governor; former Mayor of Cumberland",
    repPreviousOffice: null,
    demBio: "Dan McKee (D) became Rhode Island's governor in March 2021 when Gina Raimondo was confirmed as U.S. Secretary of Commerce. He won a full term in 2022. A former mayor and lieutenant governor, McKee has focused on economic development and infrastructure. Rhode Island is one of the most Democratic states in the country.",
    repBio: "Rhode Island Republicans are competing in the primary. Rhode Island has not elected a Republican governor since Lincoln Almond in 1998 and 2002. The state has a strong Democratic lean.",
    notes: "Cook: Solid D; IE: Solid D; Sabato: Safe D. Rhode Island is one of the most Democratic states in the country. McKee is the heavy favorite.",
  },
  {
    stateCode: "CO",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Colorado Democrats are competing in the primary to succeed term-limited Gov. Jared Polis, who has served two terms. Colorado has voted Democratic in every presidential election since 2008 and has a growing Democratic lean. The Democratic primary is June 30, 2026.",
    repBio: "Colorado Republicans are competing in the primary, hoping to flip the governorship in a state that has trended increasingly Democratic. Republicans have not won the Colorado governorship since Bill Owens in 2002. The Republican primary is June 30, 2026.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Open seat — Polis is term-limited. Colorado has a growing Democratic lean.",
  },
  {
    stateCode: "IL",
    demCandidate: "JB Pritzker",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Illinois (2019–present); businessman and philanthropist; heir to Hyatt Hotels fortune",
    repPreviousOffice: null,
    demBio: "JB Pritzker (D) won the Illinois governorship in 2018 by 16 points and was re-elected in 2022 by 12 points. A billionaire businessman and heir to the Hyatt Hotels fortune, he has self-funded much of his campaigns. Pritzker has focused on progressive priorities including abortion rights, gun safety, and education. He is seeking a third term.",
    repBio: "Illinois Republicans are competing in the primary to challenge Gov. JB Pritzker. Illinois has not elected a Republican governor since Bruce Rauner in 2014, and Pritzker's large financial advantage makes him a formidable incumbent.",
    notes: "Cook: Solid D; IE: Solid D; Sabato: Safe D. Pritzker won 2022 by 12pts. Illinois has a strong Democratic lean.",
  },
  {
    stateCode: "MD",
    demCandidate: "Wes Moore",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Maryland (2023–present); author; Army veteran; CEO, Robin Hood Foundation",
    repPreviousOffice: null,
    demBio: "Wes Moore (D) won the Maryland governorship in 2022 by 32 points, becoming the state's first Black governor and only the third Black governor elected in U.S. history. An Army combat veteran, Rhodes Scholar, and bestselling author, Moore has become one of the most prominent Democrats in the country. He has focused on economic opportunity, public safety, and education.",
    repBio: "Maryland Republicans are competing in the primary to challenge Gov. Wes Moore. Maryland has not elected a Republican governor since Larry Hogan in 2014 and 2018, and Moore's high approval ratings make him a heavy favorite.",
    notes: "Cook: Solid D; IE: Solid D; Sabato: Safe D. Moore won 2022 by 32pts. Maryland is one of the most Democratic states in the country.",
  },
  {
    stateCode: "MA",
    demCandidate: "Maura Healey",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Massachusetts (2023–present); former MA Attorney General (2015–2023)",
    repPreviousOffice: null,
    demBio: "Maura Healey (D) won the Massachusetts governorship in 2022 by 29 points, succeeding Republican Charlie Baker. She is the first openly lesbian governor in U.S. history and the first woman elected governor of Massachusetts. A former state Attorney General, she has focused on housing affordability, climate policy, and healthcare.",
    repBio: "Massachusetts Republicans are competing in the primary. Massachusetts has one of the strongest Democratic leans in the country, and Healey's high approval ratings make her a heavy favorite.",
    notes: "Cook: Solid D; IE: Solid D; Sabato: Safe D. Healey won 2022 by 29pts. Massachusetts is one of the most Democratic states in the country.",
  },
  {
    stateCode: "CT",
    demCandidate: "Ned Lamont",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Connecticut (2019–present); businessman; former Greenwich First Selectman",
    repPreviousOffice: null,
    demBio: "Ned Lamont (D) won the Connecticut governorship in 2018 and was re-elected in 2022 by 12 points. A businessman and cable TV entrepreneur, he has focused on fiscal discipline, economic development, and infrastructure. Connecticut has voted Democratic in every presidential election since 1988.",
    repBio: "Connecticut Republicans are competing in the primary to challenge Gov. Ned Lamont. Connecticut has a strong Democratic lean and Lamont's incumbency advantage makes him the heavy favorite.",
    notes: "Cook: Likely D; IE: Likely D; Sabato: Likely D. Lamont won 2022 by 12pts. Connecticut has a strong Democratic lean.",
  },
  {
    stateCode: "HI",
    demCandidate: "Josh Green",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: "Governor of Hawaii (2023–present); former Lieutenant Governor; physician",
    repPreviousOffice: null,
    demBio: "Josh Green (D) won the Hawaii governorship in 2022 by 61 points. A physician and former state senator and lieutenant governor, he has focused on housing, healthcare, and economic recovery after the 2023 Maui wildfires. Hawaii is one of the most Democratic states in the country.",
    repBio: "Hawaii Republicans are competing in the primary. Hawaii has not elected a Republican governor since Linda Lingle in 2002 and 2006. The state has an overwhelming Democratic lean.",
    notes: "Cook: Solid D; IE: Solid D; Sabato: Safe D. Green won 2022 by 61pts. Hawaii is one of the most Democratic states in the country.",
  },
  {
    stateCode: "CA",
    demCandidate: "TBD (D Primary — top-two)",
    repCandidate: "TBD (R Primary — top-two)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "California uses a top-two primary system, meaning the two candidates with the most votes advance to the general election regardless of party. Democratic candidates include Rep. Eric Swalwell, former L.A. Mayor Antonio Villaraigosa, Rep. Katie Porter, and businessman Tom Steyer, among others. The primary is June 2, 2026. Gov. Gavin Newsom is term-limited.",
    repBio: "California Republicans are competing in the top-two primary, hoping to advance a candidate to the general election. California has not elected a Republican governor since Arnold Schwarzenegger in 2006. Republicans have a significant registration disadvantage but may advance a candidate in the top-two system.",
    notes: "Cook: Solid D; IE: Solid D; Sabato: Safe D. Open seat — Newsom is term-limited. California uses a top-two primary. Multiple prominent Democrats are running.",
  },
  // ── LIKELY R RACES ──────────────────────────────────────────────────────────
  {
    stateCode: "NV",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Joe Lombardo",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of Nevada (2023–present); former Clark County Sheriff (2014–2022)",
    demBio: "Nevada Democrats are competing in the primary to challenge Gov. Joe Lombardo. Nevada is a true battleground state — Trump won it by 3.1 points in 2024. Democrats have a registration advantage but Republicans have been competitive in recent cycles.",
    repBio: "Joe Lombardo (R) won the Nevada governorship in 2022 by 1.4 points over incumbent Steve Sisolak. A former Clark County Sheriff and Las Vegas Metropolitan Police Department officer, he has focused on public safety, tax relief, and education reform. Lombardo is seeking re-election in a competitive state.",
    notes: "Cook: Lean R; IE: Lean R; Sabato: Lean R. Lombardo won 2022 by 1.4pts. Nevada is a battleground — Trump won it by 3.1pts in 2024. Lombardo is the slight favorite as incumbent.",
  },
  {
    stateCode: "NH",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Kelly Ayotte",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of New Hampshire (2025–present); former U.S. Senator, NH (2011–2017); former NH Attorney General",
    demBio: "New Hampshire Democrats are competing in the primary to challenge Gov. Kelly Ayotte. New Hampshire is a competitive state — Trump won it by 2.8 points in 2024. Democrats have won the governorship in recent cycles and will field a competitive candidate.",
    repBio: "Kelly Ayotte (R) won the New Hampshire governorship in 2024, defeating Democrat Joyce Craig by 2 points. A former U.S. Senator and state Attorney General, Ayotte is a moderate Republican who has focused on fiscal responsibility, public safety, and economic development. She is seeking her first full term as governor.",
    notes: "Cook: Lean R; IE: Lean R; Sabato: Lean R. Ayotte won 2024 by 2pts. New Hampshire is competitive — Trump won it by 2.8pts in 2024. Ayotte is the slight favorite as incumbent.",
  },
  // ── SOLID R RACES ──────────────────────────────────────────────────────────
  {
    stateCode: "AL",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Alabama Democrats are fielding candidates in the primary. Alabama is one of the most Republican states in the country and has not elected a Democratic governor since Don Siegelman in 1998.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Kay Ivey, who won re-election in 2022 by 36 points. The Republican nominee is the heavy favorite in November.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — Ivey is term-limited. Alabama is one of the most Republican states in the country.",
  },
  {
    stateCode: "AK",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Alaska Democrats and independents are competing in the primary. Alaska uses ranked-choice voting. The state has a history of electing independent and moderate candidates, but Republicans hold a significant advantage at the statewide level.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Mike Dunleavy. Alaska uses ranked-choice voting, which can benefit moderate candidates. The Republican nominee is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — Dunleavy is term-limited. Alaska uses ranked-choice voting.",
  },
  {
    stateCode: "AR",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Sarah Huckabee Sanders",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of Arkansas (2023–present); former White House Press Secretary (2017–2019); daughter of former Gov. Mike Huckabee",
    demBio: "Arkansas Democrats are fielding candidates in the primary. Arkansas is one of the most Republican states in the country and has not elected a Democratic governor since Mike Beebe in 2010.",
    repBio: "Sarah Huckabee Sanders (R) won the Arkansas governorship in 2022 by 65.7 points, the largest margin in Arkansas gubernatorial history. The daughter of former Gov. Mike Huckabee, she served as White House Press Secretary under President Trump from 2017 to 2019. She is seeking re-election and is the overwhelming favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Sanders won 2022 by 65.7pts. Arkansas is one of the most Republican states in the country.",
  },
  {
    stateCode: "FL",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Florida Democrats are competing in the primary to succeed term-limited Gov. Ron DeSantis. Florida has trended Republican in recent cycles — Trump won it by 13.3 points in 2024 — making this a difficult environment for Democrats.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Ron DeSantis. Florida has become a reliably Republican state at the statewide level, and the Republican nominee is the heavy favorite in November.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — DeSantis is term-limited. Trump won FL by 13.3pts in 2024. Republicans are the heavy favorite.",
  },
  {
    stateCode: "ID",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Brad Little",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of Idaho (2019–present); former Lieutenant Governor; rancher and businessman",
    demBio: "Idaho Democrats are fielding candidates in the primary. Idaho is one of the most Republican states in the country and has not elected a Democratic governor since Cecil Andrus in 1990.",
    repBio: "Brad Little (R) won the Idaho governorship in 2018 and was re-elected in 2022 by 59 points. A rancher and businessman, he has focused on tax relief, education reform, and economic development. He is seeking a third term and is the overwhelming favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Little won 2022 by 59pts. Idaho is one of the most Republican states in the country.",
  },
  {
    stateCode: "IA",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Iowa Democrats are competing in the primary. Iowa has trended Republican in recent cycles — Trump won it by 13.7 points in 2024. Democrats have not won the Iowa governorship since Chet Culver in 2006.",
    repBio: "Multiple Republicans are competing in the primary to succeed Gov. Kim Reynolds, who chose not to seek re-election. Iowa has trended Republican and the Republican nominee is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — Reynolds chose not to seek re-election. Iowa has trended heavily Republican.",
  },
  {
    stateCode: "NE",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Jim Pillen",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of Nebraska (2023–present); University of Nebraska Board of Regents; hog farmer and businessman",
    demBio: "Nebraska Democrats are fielding candidates in the primary. Nebraska is a reliably Republican state and has not elected a Democratic governor since Ben Nelson in 1994.",
    repBio: "Jim Pillen (R) won the Nebraska governorship in 2022 by 30 points. A hog farmer, businessman, and former University of Nebraska Board of Regents member, he has focused on tax relief and fiscal conservatism. He is seeking re-election and is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Pillen won 2022 by 30pts. Nebraska is a reliably Republican state.",
  },
  {
    stateCode: "OK",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Oklahoma Democrats are fielding candidates in the primary. Oklahoma is one of the most Republican states in the country and has not elected a Democratic governor since Brad Henry in 2006.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Kevin Stitt. Oklahoma is a reliably Republican state and the Republican nominee is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — Stitt is term-limited. Oklahoma is one of the most Republican states in the country.",
  },
  {
    stateCode: "SC",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "South Carolina Democrats are fielding candidates in the primary. South Carolina is a reliably Republican state and has not elected a Democratic governor since Jim Hodges in 1998.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Henry McMaster. South Carolina is a reliably Republican state and the Republican nominee is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — McMaster is term-limited. South Carolina is a reliably Republican state.",
  },
  {
    stateCode: "SD",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Larry Rhoden",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of South Dakota (2024–present); former Lieutenant Governor; former state legislator",
    demBio: "South Dakota Democrats are fielding candidates in the primary. South Dakota is a reliably Republican state and has not elected a Democratic governor since Richard Kneip in 1974.",
    repBio: "Larry Rhoden (R) became South Dakota's governor in January 2024 when Kristi Noem was confirmed as U.S. Secretary of Homeland Security. A former state legislator and lieutenant governor, he is seeking a full term. He is the overwhelming favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Rhoden assumed office when Noem joined the Trump Cabinet. South Dakota is a reliably Republican state.",
  },
  {
    stateCode: "TN",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Tennessee Democrats are fielding candidates in the primary. Tennessee is a reliably Republican state and has not elected a Democratic governor since Phil Bredesen in 2006.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Bill Lee. Tennessee is a reliably Republican state and the Republican nominee is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — Lee is term-limited. Tennessee is a reliably Republican state.",
  },
  {
    stateCode: "TX",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Greg Abbott",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of Texas (2015–present); former TX Attorney General (1999–2015); former TX Supreme Court Justice",
    demBio: "Texas Democrats are competing in the primary. Texas has trended slightly more competitive in recent cycles but remains a Republican-leaning state. Trump won it by 14.2 points in 2024.",
    repBio: "Greg Abbott (R) has served as Texas governor since 2015, winning re-election in 2018 and 2022 by 11 points. A former state Supreme Court Justice and Attorney General, he has focused on border security, tax relief, and economic development. Abbott is seeking a fourth term and is the heavy favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Abbott won 2022 by 11pts. Texas is a reliably Republican state at the statewide level.",
  },
  {
    stateCode: "VT",
    demCandidate: "TBD (D Primary)",
    repCandidate: "Phil Scott",
    demPreviousOffice: null,
    repPreviousOffice: "Governor of Vermont (2017–present); former Lieutenant Governor; businessman",
    demBio: "Vermont Democrats are competing in the primary. Vermont is one of the most Democratic states in the country at the presidential level, but has a history of electing moderate Republican governors.",
    repBio: "Phil Scott (R) has served as Vermont's governor since 2017, winning re-election in 2018, 2020, 2022, and 2024 by large margins. A moderate Republican who has frequently clashed with the Trump wing of the party, he has focused on fiscal responsibility, housing, and climate policy. Scott is seeking a fifth term.",
    notes: "Cook: Likely R; IE: Likely R; Sabato: Likely R. Scott won 2024 by 27pts. Vermont has a history of electing moderate Republican governors despite being a very blue state at the presidential level.",
  },
  {
    stateCode: "WY",
    demCandidate: "TBD (D Primary)",
    repCandidate: "TBD (R Primary)",
    demPreviousOffice: null,
    repPreviousOffice: null,
    demBio: "Wyoming Democrats are fielding candidates in the primary. Wyoming is the most Republican state in the country by presidential margin — Trump won it by 43.3 points in 2024.",
    repBio: "Multiple Republicans are competing in the primary to succeed term-limited Gov. Mark Gordon. Wyoming is the most Republican state in the country and the Republican nominee is the overwhelming favorite.",
    notes: "Cook: Solid R; IE: Solid R; Sabato: Safe R. Open seat — Gordon is term-limited. Wyoming is the most Republican state in the country.",
  },
];

let updated = 0;
let errors = 0;

for (const race of bioupdates) {
  try {
    const [result] = await conn.execute(
      `UPDATE governor_races SET 
        dem_candidate = ?,
        rep_candidate = ?,
        dem_previous_office = ?,
        rep_previous_office = ?,
        dem_bio = ?,
        rep_bio = ?,
        notes = ?
       WHERE state_code = ?`,
      [
        race.demCandidate,
        race.repCandidate,
        race.demPreviousOffice ?? null,
        race.repPreviousOffice ?? null,
        race.demBio,
        race.repBio,
        race.notes,
        race.stateCode,
      ]
    );
    if (result.affectedRows > 0) {
      updated++;
      console.log(`✓ ${race.stateCode} updated`);
    } else {
      console.log(`⚠ ${race.stateCode} — no row found`);
    }
  } catch (err) {
    errors++;
    console.error(`✗ ${race.stateCode} error:`, err.message);
  }
}

console.log(`\nDone: ${updated} updated, ${errors} errors`);
await conn.end();
