import mysql from 'mysql2/promise';
import * as dotenv from 'dotenv';
dotenv.config({ path: '/home/ubuntu/election-map-2026/.env' });

const conn = await mysql.createConnection(process.env.DATABASE_URL);

const races = [
  {
    stateCode: 'AL',
    demCandidate: 'Doug Jones',
    demPreviousOffice: 'U.S. Senator from Alabama (2018–2021)',
    demBio: 'Former U.S. Senator who served from 2018 to 2021. Previously a U.S. Attorney and lead prosecutor in the reopened 1963 Birmingham church bombing case. Running in a crowded Democratic primary that also includes Will Boyd and Ja\'Mel Brown.',
    repCandidate: 'Tommy Tuberville',
    repPreviousOffice: 'U.S. Senator from Alabama (2021–2027)',
    repBio: 'U.S. Senator from Alabama and former college football head coach who led Auburn University to an undefeated season. Running in a Republican primary that includes Ken McFeeters and Will Santivasci.',
    incumbent: 'Kay Ivey',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'AK',
    demCandidate: 'Tom Begich',
    demPreviousOffice: 'Alaska State Senator, District J',
    demBio: 'Former Democratic member of the Alaska Senate and grandson of former U.S. Representative Nick Begich. Also a musician and consultant. Primary field also includes Matt Claman and Jonathan Kreiss-Tomkins.',
    repCandidate: 'Nancy Dahlstrom',
    repPreviousOffice: 'Lieutenant Governor of Alaska (2022–present)',
    repBio: 'Current Lieutenant Governor of Alaska. Crowded Republican primary also includes Click Bishop (former State Senator), David Bronson (former Anchorage Mayor), Adam Crum (Revenue Commissioner), Edna DeVries (Mat-Su Borough Mayor), and Shelley Hughes.',
    incumbent: 'Mike Dunleavy',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'AZ',
    demCandidate: 'Katie Hobbs',
    demPreviousOffice: 'Governor of Arizona (2023–present)',
    demBio: 'The 24th Governor of Arizona, serving since January 2023. Former Arizona Secretary of State (2019–2023). Won the 2022 governor\'s race by just 0.6 percentage points over Kari Lake.',
    repCandidate: 'Andy Biggs',
    repPreviousOffice: 'U.S. Representative, AZ-5 (2017–2025)',
    repBio: 'Former U.S. Representative for Arizona\'s 5th congressional district and former Arizona Senate President. Conservative firebrand and close Trump ally. Republican primary also includes Ken Miceli, Scott Neely, and David Schweikert.',
    incumbent: 'Katie Hobbs',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'AR',
    demCandidate: 'Fredrick Love',
    demPreviousOffice: 'Arkansas State Senate, District 15',
    demBio: 'Democratic member of the Arkansas State Senate representing District 15. Previously served multiple terms in the Arkansas House of Representatives. Won the Democratic primary over Supha Xayprasith-Mays.',
    repCandidate: 'Sarah Huckabee Sanders',
    repPreviousOffice: 'Governor of Arkansas (2023–present)',
    repBio: 'The 47th Governor of Arkansas, serving since January 2023. Previously served as White House Press Secretary under President Trump (2017–2019). The Republican primary was canceled; she advanced unopposed.',
    incumbent: 'Sarah Huckabee Sanders',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'CA',
    demCandidate: 'Antonio Villaraigosa',
    demPreviousOffice: 'Mayor of Los Angeles (2005–2013)',
    demBio: 'Former Mayor of Los Angeles and former Speaker of the California State Assembly. Running in a crowded top-two primary alongside Xavier Becerra (former HHS Secretary), Katie Porter (former U.S. Rep), Matt Mahan (San Jose Mayor), Thomas Steyer (businessman), and Eric Swalwell (U.S. Rep).',
    repCandidate: 'Chad Bianco',
    repPreviousOffice: 'Sheriff-Coroner of Riverside County (2018–present)',
    repBio: 'Elected Sheriff-Coroner of Riverside County in 2018 after 26 years at the department. A vocal critic of California\'s progressive policies. Republican primary also includes Steve Hilton (former Fox News host and tech entrepreneur).',
    incumbent: 'Gavin Newsom',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'CO',
    demCandidate: 'Michael Bennet',
    demPreviousOffice: 'U.S. Senator from Colorado (2009–present)',
    demBio: 'Senior U.S. Senator from Colorado since 2009. Former superintendent of Denver Public Schools. Widely regarded as a pragmatic centrist. Gave up his Senate seat to run for governor.',
    repCandidate: 'Greg Lopez',
    repPreviousOffice: 'U.S. Representative, CO-4 (2024–2025)',
    repBio: 'Former U.S. Representative for Colorado\'s 4th congressional district. Previously served as Mayor of Parker, Colorado. Running on a platform of fiscal conservatism and reducing government regulation.',
    incumbent: 'Jared Polis',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'CT',
    demCandidate: 'Ned Lamont',
    demPreviousOffice: 'Governor of Connecticut (2019–present)',
    demBio: 'The 89th Governor of Connecticut, serving since 2019. Founder of Lamont Digital Systems, a telecommunications company. Seeking a third term; faces a primary challenge from Joshua Elliott.',
    repCandidate: 'Erin Stewart',
    repPreviousOffice: 'Mayor of New Britain, Connecticut (2013–2023)',
    repBio: 'Former Mayor of New Britain, Connecticut, serving from 2013 to 2023. One of the longest-serving mayors in New Britain history. Republican primary also includes Ryan Fazio (State Senator), Betsy McCaughey (former NY Lt. Governor), and Timothy Wilcox.',
    incumbent: 'Ned Lamont',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'FL',
    demCandidate: 'Jerry Demings',
    demPreviousOffice: 'Orange County Mayor (2018–present)',
    demBio: 'Current Mayor of Orange County, Florida. Former Orange County Sheriff (2008–2018) and former Orlando Police Chief. Primary field also includes David Jolly (former Republican U.S. Representative who switched parties).',
    repCandidate: 'Byron Donalds',
    repPreviousOffice: 'U.S. Representative, FL-19 (2021–present)',
    repBio: 'U.S. Representative for Florida\'s 19th congressional district and prominent Trump ally. Republican primary also includes Jay Collins (Lt. Governor), Paul Renner (former House Speaker), and James Fishback (investment firm CEO).',
    incumbent: 'Ron DeSantis',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'GA',
    demCandidate: 'Keisha Lance Bottoms',
    demPreviousOffice: 'Mayor of Atlanta (2018–2022)',
    demBio: 'Former Mayor of Atlanta (2018–2022) and senior adviser to President Biden. Previously a member of the Atlanta City Council. Democratic primary also includes Geoff Duncan (former Lt. Governor), Jason Esteves, and Michael Thurmond.',
    repCandidate: 'Chris Carr',
    repPreviousOffice: 'Attorney General of Georgia (2016–present)',
    repBio: 'The 48th Attorney General of Georgia, serving since 2016. Won statewide election twice (2018 and 2022). Republican primary also includes Lt. Governor Burt Jones, Secretary of State Brad Raffensperger, and several others.',
    incumbent: 'Brian Kemp',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'HI',
    demCandidate: 'Josh Green',
    demPreviousOffice: 'Governor of Hawaii (2023–present)',
    demBio: 'The 9th Governor of Hawaii, serving since December 2022. A physician by training, he previously served as Lieutenant Governor and a state senator. Seeking re-election in a solidly Democratic state.',
    repCandidate: 'TBD',
    repPreviousOffice: 'TBD',
    repBio: 'No major Republican candidate has declared as of April 2026. Hawaii is a strongly Democratic state.',
    incumbent: 'Josh Green',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'ID',
    demCandidate: 'Terri Pickens',
    demPreviousOffice: 'Founder, Pickens Law P.A.',
    demBio: 'Fourth-generation Idahoan and attorney who founded her own law firm. Previously ran for Lieutenant Governor in 2022. Democratic primary also includes Maxine Durand and Chanelle Torrez.',
    repCandidate: 'Brad Little',
    repPreviousOffice: 'Governor of Idaho (2019–present)',
    repBio: 'The 33rd Governor of Idaho, serving since 2019. A rancher and businessman who previously served as Lieutenant Governor. Seeking a third term; faces several primary challengers including Mark Fitzpatrick and Sean Crystal.',
    incumbent: 'Brad Little',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'IL',
    demCandidate: 'J.B. Pritzker',
    demPreviousOffice: 'Governor of Illinois (2019–present)',
    demBio: 'The 43rd Governor of Illinois, serving since 2019. An heir to the Hyatt Hotel chain who has focused on progressive policies including expanded healthcare and education funding. Seeking a third term in a rematch of 2022.',
    repCandidate: 'Darren Bailey',
    repPreviousOffice: 'Illinois State Senate (2021–2023)',
    repBio: 'Farmer and former Illinois State Senator and House member. Was the 2022 Republican gubernatorial nominee, losing to Pritzker by 12 points. Running again in a rematch — the first such gubernatorial rematch since 1986.',
    incumbent: 'J.B. Pritzker',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'IA',
    demCandidate: 'Rob Sand',
    demPreviousOffice: 'Iowa Auditor of State (2019–present)',
    demBio: 'Current Iowa Auditor of State, serving since 2019. The only Democrat currently holding statewide office in Iowa. Running as the sole major Democratic candidate in an open-seat race.',
    repCandidate: 'Randy Feenstra',
    repPreviousOffice: 'U.S. Representative, IA-4 (2021–present)',
    repBio: 'U.S. Representative for Iowa\'s 4th congressional district since 2021. Republican primary also includes Eddie Andrews (State Rep), Zach Lahn, Brad Sherman, and Adam Steen (former state agency director).',
    incumbent: 'Kim Reynolds',
    isTermLimited: false,
    isOpen: true,
  },
  {
    stateCode: 'KS',
    demCandidate: 'Cindy Holscher',
    demPreviousOffice: 'Kansas State Senate, District 7 (2021–present)',
    demBio: 'Member of the Kansas State Senate representing District 7. Attorney and former Johnson County District Court judge. Democratic primary also includes Ethan Corson (State Senator, District 7).',
    repCandidate: 'Ty Masterson',
    repPreviousOffice: 'Kansas State Senate President (2021–present)',
    repBio: 'Current President of the Kansas State Senate, representing District 16. Previously served in the Kansas House of Representatives and on the Andover City Council. Republican primary also includes Charlotte O\'Hara, Joy Eakins, and Doug Billings.',
    incumbent: 'Laura Kelly',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'ME',
    demCandidate: 'Shenna Bellows',
    demPreviousOffice: 'Secretary of State of Maine (2019–present)',
    demBio: 'The 50th Secretary of State of Maine, serving since 2019. Civil rights advocate and former ACLU Maine director. Democratic primary also includes Senate President Troy Jackson, Angus King III (son of Sen. Angus King), former House Speaker Hannah Pingree, and Dr. Nirav Shah.',
    repCandidate: 'Garrett Mason',
    repPreviousOffice: 'Maine State Senate Majority Leader',
    repBio: 'Former Maine State Senator and Senate Majority Leader. Republican primary also includes Jonathan Bush (co-founder of athenahealth), Bobby Charles (former Asst. Secretary of State), Ben Midgley (former Planet Fitness president), and James Libby.',
    incumbent: 'Janet Mills',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'MD',
    demCandidate: 'Wes Moore',
    demPreviousOffice: 'Governor of Maryland (2023–present)',
    demBio: 'The 63rd Governor of Maryland and the state\'s first Black governor, serving since January 2023. Combat veteran, bestselling author, and former CEO of Robin Hood Foundation. Seeking re-election; faces a minor primary challenge from Eric Felber.',
    repCandidate: 'Dan Cox',
    repPreviousOffice: 'Maryland House of Delegates (2019–2023)',
    repBio: 'Former member of the Maryland House of Delegates. Was the 2022 Republican gubernatorial nominee, losing to Moore by 32 points. Running again in 2026. Primary also includes John Myrick.',
    incumbent: 'Wes Moore',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'MA',
    demCandidate: 'Maura Healey',
    demPreviousOffice: 'Governor of Massachusetts (2023–present)',
    demBio: 'The 73rd Governor of Massachusetts and the first openly lesbian governor in U.S. history, serving since January 2023. Former Massachusetts Attorney General (2015–2023). Seeking re-election; faces minor primary challenges from Matthew Dewar and Andrea James.',
    repCandidate: 'Mike Kennealy',
    repPreviousOffice: 'Massachusetts Secretary of Housing and Economic Development',
    repBio: 'Former Massachusetts Secretary of Housing and Economic Development under Governor Charlie Baker. Running as a moderate Republican in a heavily Democratic state.',
    incumbent: 'Maura Healey',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'MI',
    demCandidate: 'Jocelyn Benson',
    demPreviousOffice: 'Michigan Secretary of State (2019–present)',
    demBio: 'Current Michigan Secretary of State, serving since 2019. Civil rights advocate and the youngest woman dean of an accredited law school in U.S. history. Democratic primary also includes Chris Swanson (Genesee County Sheriff), Kim Thomas, Kevin Hogan, and Marni Sawicki.',
    repCandidate: 'John James',
    repPreviousOffice: 'U.S. Representative, MI-10 (2023–present)',
    repBio: 'U.S. Representative for Michigan\'s 10th congressional district since 2023. Army combat veteran and businessman. Republican primary also includes Mike Cox (former AG), Tom Leonard (former House Speaker), Aric Nesbitt (State Senate Majority Leader), and others.',
    incumbent: 'Gretchen Whitmer',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'MN',
    demCandidate: 'Amy Klobuchar',
    demPreviousOffice: 'U.S. Senator from Minnesota (2007–present)',
    demBio: 'Senior U.S. Senator from Minnesota since 2007. Former Hennepin County Attorney. 2020 presidential candidate. Gave up her Senate seat to run for governor. Democratic primary also includes Mandela Barnes (former Lt. Governor), Sara Rodriguez (Lt. Governor), and others.',
    repCandidate: 'Lisa Demuth',
    repPreviousOffice: 'Minnesota House Minority Leader',
    repBio: 'Current Minnesota House Minority Leader. Republican primary also includes Kendall Qualls (former congressional candidate), Peggy Bennett (State Rep), and Mike Lindell (MyPillow CEO).',
    incumbent: 'Tim Walz',
    isTermLimited: false,
    isOpen: true,
  },
  {
    stateCode: 'NE',
    demCandidate: 'Lynne Walz',
    demPreviousOffice: 'Nebraska State Senator (2017–2025)',
    demBio: 'Former Nebraska State Senator who served in the unicameral legislature from 2017 to 2025. Running on a platform of bringing people together to solve problems. Primary also includes Larry Marvin.',
    repCandidate: 'Jim Pillen',
    repPreviousOffice: 'Governor of Nebraska (2023–present)',
    repBio: 'The 41st Governor of Nebraska, serving since January 2023. Veterinarian and livestock producer who grew up on a farm in Platte County. Seeking re-election; faces a Republican primary with several challengers including Sal Holguin and Sheila Korth-Focken.',
    incumbent: 'Jim Pillen',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'NV',
    demCandidate: 'Aaron Ford',
    demPreviousOffice: 'Attorney General of Nevada (2019–present)',
    demBio: 'The 34th Attorney General of Nevada, serving since 2019. Former Majority Leader of the Nevada State Senate. Democratic primary also includes Alexis Hill (Washoe County Commissioner), James Cooper (State Assemblyman), and others.',
    repCandidate: 'Joe Lombardo',
    repPreviousOffice: 'Governor of Nevada (2023–present)',
    repBio: 'The 31st Governor of Nevada, elected in 2022. Former Sheriff of Clark County. Seeking re-election in a competitive swing state. Faces a minor Republican primary.',
    incumbent: 'Joe Lombardo',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'NH',
    demCandidate: 'Cinde Warmington',
    demPreviousOffice: 'Executive Councilor, District 2 (2020–2024)',
    demBio: 'Attorney and former Executive Councilor for District 2. Was the 2024 Democratic gubernatorial nominee, losing to Kelly Ayotte. Running again in 2026 as the leading Democratic challenger.',
    repCandidate: 'Kelly Ayotte',
    repPreviousOffice: 'Governor of New Hampshire (2025–present)',
    repBio: 'The 83rd Governor of New Hampshire, serving since January 2025. Former U.S. Senator from New Hampshire (2011–2017) and former state Attorney General. Seeking re-election in her first term.',
    incumbent: 'Kelly Ayotte',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'NM',
    demCandidate: 'Debra Haaland',
    demPreviousOffice: 'U.S. Secretary of the Interior (2021–2025)',
    demBio: 'Former U.S. Secretary of the Interior (2021–2025) and the first Native American to serve as a cabinet secretary. Former U.S. Representative for NM-1 (2019–2021). Democratic primary also includes Sam Bregman (Bernalillo County DA).',
    repCandidate: 'Gregg Hull',
    repPreviousOffice: 'Mayor of Rio Rancho',
    repBio: 'Current Mayor of Rio Rancho, New Mexico\'s second-largest city. Republican primary also includes Duke Rodriguez (cannabis CEO and former state cabinet secretary) and Doug Turner (entrepreneur).',
    incumbent: 'Michelle Lujan Grisham',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'NY',
    demCandidate: 'Kathy Hochul',
    demPreviousOffice: 'Governor of New York (2021–present)',
    demBio: 'The 57th and first female Governor of New York, serving since August 2021. Former Lieutenant Governor and U.S. Representative for NY-26. Seeking a second full term; faces a minor primary challenge from John Rinaldi.',
    repCandidate: 'Bruce Blakeman',
    repPreviousOffice: 'Nassau County Executive (2022–present)',
    repBio: 'Current Nassau County Executive, serving since 2022. Previously served as a Hempstead Town Councilman. Running as the leading Republican challenger in a heavily Democratic state.',
    incumbent: 'Kathy Hochul',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'OH',
    demCandidate: 'Amy Acton',
    demPreviousOffice: 'Director, Ohio Department of Health (2019–2020)',
    demBio: 'Physician and researcher who served as Director of the Ohio Department of Health during the COVID-19 pandemic, gaining national recognition for her briefings. Running as the sole major Democratic candidate.',
    repCandidate: 'Vivek Ramaswamy',
    repPreviousOffice: 'Biotech entrepreneur; 2024 presidential candidate',
    repBio: 'Biotech entrepreneur and 2024 Republican presidential candidate who dropped out and endorsed Donald Trump. Co-founded Roivant Sciences. Republican primary also includes Heather Hill and Casey Putsch.',
    incumbent: 'Mike DeWine',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'OK',
    demCandidate: 'Cyndi Munson',
    demPreviousOffice: 'Oklahoma House of Representatives, District 85 (2015–present)',
    demBio: 'Current member of the Oklahoma House of Representatives, serving since 2015. Democratic primary also includes Constance Johnson (former State Senator) and Arya.',
    repCandidate: 'Gentner Drummond',
    repPreviousOffice: 'Attorney General of Oklahoma (2023–present)',
    repBio: 'Current Attorney General of Oklahoma, serving since 2023. Republican primary also includes Mike Mazzei (former State Senator) and Jake Merrick (former State Senator).',
    incumbent: 'Kevin Stitt',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'OR',
    demCandidate: 'Tina Kotek',
    demPreviousOffice: 'Governor of Oregon (2023–present)',
    demBio: 'The 39th Governor of Oregon, serving since January 2023. Made history as the first openly lesbian Speaker of a state House of Representatives. Seeking re-election as the sole major Democratic candidate.',
    repCandidate: 'Christine Drazan',
    repPreviousOffice: 'Oregon State Senate, District 26 (2023–present)',
    repBio: 'Current Oregon State Senator and former House Minority Leader. Was the 2022 Republican gubernatorial nominee, losing to Kotek in a three-way race. Republican primary also includes Chris Dudley (former NBA player and 2010 gubernatorial nominee).',
    incumbent: 'Tina Kotek',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'PA',
    demCandidate: 'Josh Shapiro',
    demPreviousOffice: 'Governor of Pennsylvania (2023–present)',
    demBio: 'The 48th Governor of Pennsylvania, serving since January 2023. Former Pennsylvania Attorney General (2017–2023). Seeking re-election as the sole major Democratic candidate in a key battleground state.',
    repCandidate: 'Stacy Garrity',
    repPreviousOffice: 'Pennsylvania Treasurer (2021–present)',
    repBio: 'The 79th Pennsylvania Treasurer, serving since 2021. Former U.S. Army Reserve officer and businesswoman. Running as the leading Republican challenger to incumbent Governor Shapiro.',
    incumbent: 'Josh Shapiro',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'RI',
    demCandidate: 'Daniel McKee',
    demPreviousOffice: 'Governor of Rhode Island (2021–present)',
    demBio: 'The 76th Governor of Rhode Island, serving since March 2021 after ascending from Lt. Governor when Gina Raimondo joined the Biden cabinet. Former Mayor of Cumberland. Seeking a full second term; primary also includes Helena Foulkes and Gregory Stevens.',
    repCandidate: 'Aaron Guckian',
    repPreviousOffice: 'Former Director of Advance, Governor\'s Office',
    repBio: 'Former Director of Advance at the Governor\'s Office under Governor Carcieri. Previously ran for Lieutenant Governor in 2022. Republican primary also includes Elaine Pelino and Robert Raimondo.',
    incumbent: 'Daniel McKee',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'SC',
    demCandidate: 'Jermaine Johnson',
    demPreviousOffice: 'South Carolina House of Representatives, District 52 (2024–present)',
    demBio: 'Current member of the South Carolina House of Representatives. Democratic primary also includes Mullins McLeod (trial lawyer), Justin A. Bennett, and Billy Webster.',
    repCandidate: 'Alan Wilson',
    repPreviousOffice: 'Attorney General of South Carolina (2011–present)',
    repBio: 'Current Attorney General of South Carolina, serving since 2011. Republican primary also includes Lt. Governor Pamela Evette, U.S. Rep Nancy Mace, U.S. Rep Ralph Norman, State Senator Josh Kimbrell, and Rom Reddy.',
    incumbent: 'Henry McMaster',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'SD',
    demCandidate: 'Dan Ahlers',
    demPreviousOffice: 'Former South Dakota State Representative; Executive Director, SD Democratic Party',
    demBio: 'Businessman, community leader, and former state legislator who served in the South Dakota House of Representatives. Also served as Executive Director of the South Dakota Democratic Party. Primary also includes Robert Arnold (19-year-old student).',
    repCandidate: 'Dusty Johnson',
    repPreviousOffice: 'U.S. Representative, SD-AL (2019–present)',
    repBio: 'U.S. Representative for South Dakota\'s at-large congressional district since 2019. Republican primary also includes incumbent Governor Larry Rhoden, Speaker Jon Hansen, and Toby Doeden.',
    incumbent: 'Larry Rhoden',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'TN',
    demCandidate: 'Carnita Atwater',
    demPreviousOffice: 'Community Advocate',
    demBio: 'Lifelong community advocate running to be the first woman of color governor of Tennessee. Democratic primary also includes Tim Cyr, Jerri Green, Adam Kurtz, and Kevin Lee McCants.',
    repCandidate: 'Marsha Blackburn',
    repPreviousOffice: 'U.S. Senator from Tennessee (2019–present)',
    repBio: 'Senior U.S. Senator from Tennessee, serving since 2019. Previously served in the U.S. House of Representatives (2003–2019) and the Tennessee State Senate. Republican primary also includes John Rose (former U.S. Rep) and Monty Fritts.',
    incumbent: 'Bill Lee',
    isTermLimited: true,
    isOpen: true,
  },
  {
    stateCode: 'TX',
    demCandidate: 'Gina Hinojosa',
    demPreviousOffice: 'Texas House of Representatives (2017–present)',
    demBio: 'Current member of the Texas House of Representatives, serving since 2017. Attorney and advocate for Texas families. Won the Democratic primary as the sole major Democratic candidate.',
    repCandidate: 'Greg Abbott',
    repPreviousOffice: 'Governor of Texas (2015–present)',
    repBio: 'The 48th Governor of Texas, serving since 2015. Former Texas Attorney General (1999–2015). Seeking a fourth term in a solidly Republican state.',
    incumbent: 'Greg Abbott',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'VT',
    demCandidate: 'Aly Richards',
    demPreviousOffice: 'Former CEO of Let\'s Grow Kids',
    demBio: 'Former CEO of Let\'s Grow Kids, a Vermont nonprofit focused on early childhood education. Democratic primary also includes Amanda Janoo (economist and policy expert).',
    repCandidate: 'Phil Scott',
    repPreviousOffice: 'Governor of Vermont (2017–present)',
    repBio: 'The 82nd Governor of Vermont, serving since January 2017. Moderate Republican who has won re-election four times in a heavily Democratic state. Seeking a fifth term in 2026.',
    incumbent: 'Phil Scott',
    isTermLimited: false,
    isOpen: false,
  },
  {
    stateCode: 'WI',
    demCandidate: 'Mandela Barnes',
    demPreviousOffice: 'Lieutenant Governor of Wisconsin (2019–2023)',
    demBio: 'Former Lieutenant Governor of Wisconsin (2019–2023) and former Wisconsin State Assembly member. Was the 2022 Democratic U.S. Senate nominee, losing to Ron Johnson by 1 point. Democratic primary also includes Sara Rodriguez (current Lt. Governor), David Crowley (Milwaukee County Executive), Francesca Hong, Missy Hughes, and Joel Brennan.',
    repCandidate: 'Tom Tiffany',
    repPreviousOffice: 'U.S. Representative, WI-7 (2020–present)',
    repBio: 'U.S. Representative for Wisconsin\'s 7th congressional district since 2020. Previously served in the Wisconsin State Senate and State Assembly. Republican primary also includes Andrew Manske.',
    incumbent: 'Tony Evers',
    isTermLimited: false,
    isOpen: true,
  },
  {
    stateCode: 'WY',
    demCandidate: 'Gabriel Green',
    demPreviousOffice: 'None',
    demBio: 'Sheridan resident and Casper native running as a self-described "Democrat in Name Only" (DINO) to challenge the political establishment. Focuses on property rights, education, and energy policy.',
    repCandidate: 'Megan Degenfelder',
    repPreviousOffice: 'Wyoming Superintendent of Public Instruction (2023–present)',
    repBio: 'Current Wyoming Superintendent of Public Instruction, serving since 2023. Republican primary also includes Eric Barlow (State Senator and former House Speaker) and Brent Bien (retired Marine Colonel).',
    incumbent: 'Mark Gordon',
    isTermLimited: true,
    isOpen: true,
  },
];

console.log(`Updating ${races.length} governor races with comprehensive candidate data...`);

for (const race of races) {
  await conn.execute(
    `UPDATE governor_races SET
      dem_candidate = ?,
      dem_previous_office = ?,
      dem_bio = ?,
      rep_candidate = ?,
      rep_previous_office = ?,
      rep_bio = ?,
      incumbent_name = ?,
      is_term_limited = ?,
      is_open = ?
    WHERE state_code = ?`,
    [
      race.demCandidate,
      race.demPreviousOffice,
      race.demBio,
      race.repCandidate,
      race.repPreviousOffice,
      race.repBio,
      race.incumbent,
      race.isTermLimited ? 1 : 0,
      race.isOpen ? 1 : 0,
      race.stateCode,
    ]
  );
  console.log(`  ✓ ${race.stateCode}: ${race.demCandidate} (D) vs ${race.repCandidate} (R)`);
}

await conn.end();
console.log('\n✅ All 36 governor races updated with comprehensive candidate data!');
