CREATE TABLE `governor_races` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state_code` varchar(2) NOT NULL,
	`state_name` varchar(64) NOT NULL,
	`incumbent_name` varchar(128),
	`incumbent_party` enum('D','R','I'),
	`is_open` boolean NOT NULL DEFAULT false,
	`is_term_limited` boolean NOT NULL DEFAULT false,
	`previous_party` enum('D','R','I') NOT NULL,
	`rating` enum('Solid D','Likely D','Lean D','Toss-up','Lean R','Likely R','Solid R') NOT NULL DEFAULT 'Solid R',
	`primary_date` varchar(64),
	`runoff_date` varchar(64),
	`general_date` varchar(64) NOT NULL DEFAULT 'November 3, 2026',
	`is_special` boolean NOT NULL DEFAULT false,
	`status` enum('Scheduled','Voting','Called','Certified') NOT NULL DEFAULT 'Scheduled',
	`called_party` enum('D','R','I'),
	`dem_votes` bigint DEFAULT 0,
	`rep_votes` bigint DEFAULT 0,
	`pct_reporting` decimal(5,2) DEFAULT '0',
	`dem_candidate` varchar(128),
	`rep_candidate` varchar(128),
	`notes` text,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `governor_races_id` PRIMARY KEY(`id`),
	CONSTRAINT `governor_races_state_code_unique` UNIQUE(`state_code`)
);
